### ISSUE TITLE
Skipped keys?

### ISSUE THREAD

**Issue by bodrovis** [silbersteine/Lokalise-Manual-Trigger-Actions#19]
https://github.com/silbersteine/Lokalise-Manual-Trigger-Actions/blob/main/.github/workflows/ManualPush.yml#L63

I'm not sure we should tag skipped keys but perhaps I'm missing something here

**Comment by silbersteine** [comment]
The reason why I'm skipping keys is because it tags the keys that belong to a file that are not updated in the push. The result is ALL of a file's keys receive tags. Then, at download, we're downloading ALL of the relevant keys. Skipping any keys at download would have disastrous results because the files would miss all keys that don't have deltas.This is of course if we use key tags to accomplish pushing and pulling of files in diffs. 

There is the option to push/pull based on filename... BUt I think it may be more complicated than tags.

**Comment by bodrovis** [comment]
Okay, thank you. I guess let's leave it at that :)
